# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Algolia < Formula
  desc "FIG - Fake Insights Generator"
  homepage "https://www.algolia.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b0d592ff3d55d6490977ad16962587a7043c6b7c086794593e805c53ca9477b3"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "34f5ec0e759a7de1aa4ff10e7281756bc0ae6a48428662a3492dc92db4ed579d"

      def install
        bin.install "fig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f15fd4693249679247d738f0c2c933ac302bfffc92426197cfff04362bfd4545"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_armv6.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d71586bacc2626177f4d5099919e583eab639f3aca2f4e50c713dfb3cd29acdb"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "849802ef53383dfb5f489bdcf9bbfaa914da6f73dd5f722df1c9a6c4b6eca589"

      def install
        bin.install "fig"
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the FIG!
  EOS
  end
end
