# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Algolia < Formula
  desc "FIG - Fake Insights Generator"
  homepage "https://www.algolia.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a10db2f61f694c19c15803cee47e785c67980c9d5c55fd48ac09c7b6764e9654"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f6d8996dbf98e476c4afa16099de5d1f66da5f3233fd7b2adfb88c62e13a15f4"

      def install
        bin.install "fig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_armv6.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b304851b29d1331f806c8db364117ccd03c81e085c835e32a4cbaacec71e65cd"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e5889c5a35ce34e7fd40967c12909f8f2b39ae044e9815f5cb266f56eadf0e28"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.0.0/algolia_1.0.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "01b0c96149ce8b9eee79eac281305d7b15b0dbbdcf35d4d2a9befafb20a9fc26"

      def install
        bin.install "fig"
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the FIG!
  EOS
  end
end
