# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Fig < Formula
  desc "FIG - Fake Insights Generator"
  homepage "https://www.algolia.com"
  version "1.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.1.5/fig_1.1.5_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8c00a3cf81ae8e46070e94a7a648ae65e8399d812a67558d142b8188534801b3"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.1.5/fig_1.1.5_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a7f15decb27aa46020b0d5f4260a067908643a8cc2513677608c90beaebce119"

      def install
        bin.install "fig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.1.5/fig_1.1.5_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "433143576ea7f67c570a8a2af98f31f0684e1246141027837957669f59dcf13c"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.1.5/fig_1.1.5_linux_armv6.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0935e663cf450243cf299c2f6c215de6cdc012fdd6c0230f37adce32faec828b"

      def install
        bin.install "fig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/algolia/fake-insights-generator/releases/download/v1.1.5/fig_1.1.5_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "39c5fefaf2ca3bd73cfcf62ec532e35e3304ecb089524fd8b1c6a20947c320bc"

      def install
        bin.install "fig"
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the FIG!
  EOS
  end
end
